-- ============================================================
-- [0] CLEANUP SCRIPT (DROP TABLES IN REVERSE ORDER)
-- Run this section ONLY when you need to reset the entire schema
-- ============================================================

-- 1. Drop Multivalued Attribute Tables
DROP TABLE Dr_Phone CASCADE CONSTRAINTS;
DROP TABLE Nu_Phone CASCADE CONSTRAINTS;
DROP TABLE Ph_Phone CASCADE CONSTRAINTS;
DROP TABLE Rs_Phone CASCADE CONSTRAINTS;
DROP TABLE Patient_Phone CASCADE CONSTRAINTS;
DROP TABLE Dep_Phone CASCADE CONSTRAINTS;
DROP TABLE Chronic_Diseases CASCADE CONSTRAINTS;
DROP TABLE Allergies CASCADE CONSTRAINTS;
DROP TABLE Past_Surgeries CASCADE CONSTRAINTS;
DROP TABLE Current_Medication CASCADE CONSTRAINTS;

-- 2. Drop M:N Linking Tables (Junction Tables)
DROP TABLE Invoice_Lab_Test CASCADE CONSTRAINTS;
DROP TABLE Radiology_Scan_Invoice CASCADE CONSTRAINTS;
DROP TABLE Test_Result CASCADE CONSTRAINTS;
DROP TABLE Scan_Result CASCADE CONSTRAINTS;
DROP TABLE Dispenses CASCADE CONSTRAINTS;
DROP TABLE Prescription CASCADE CONSTRAINTS;
DROP TABLE Inventories CASCADE CONSTRAINTS;
DROP TABLE Participates_In CASCADE CONSTRAINTS;
DROP TABLE Performs CASCADE CONSTRAINTS;
DROP TABLE Undergoes CASCADE CONSTRAINTS;
DROP TABLE Supervises_Room CASCADE CONSTRAINTS;
DROP TABLE Admitted_To CASCADE CONSTRAINTS;
DROP TABLE Held_In CASCADE CONSTRAINTS;
DROP TABLE Refers CASCADE CONSTRAINTS;
DROP TABLE Appointment CASCADE CONSTRAINTS;

-- 3. Drop Weak Entities
DROP TABLE Medical_History CASCADE CONSTRAINTS;
DROP TABLE Dependent CASCADE CONSTRAINTS;

-- 4. Drop Transactional & Dependent Core Entities
DROP TABLE Invoice CASCADE CONSTRAINTS;
DROP TABLE Lab_Test CASCADE CONSTRAINTS;
DROP TABLE Radiology_Scan CASCADE CONSTRAINTS;
DROP TABLE Patient CASCADE CONSTRAINTS;

-- 5. Drop Staff Entities
DROP TABLE Pharmacist CASCADE CONSTRAINTS;
DROP TABLE Nurse CASCADE CONSTRAINTS;
DROP TABLE Doctors CASCADE CONSTRAINTS;
DROP TABLE Receptionist CASCADE CONSTRAINTS;

-- 6. Drop Root Entities (Independent)
DROP TABLE Department CASCADE CONSTRAINTS;
DROP TABLE Insurance CASCADE CONSTRAINTS;
DROP TABLE Room CASCADE CONSTRAINTS;
DROP TABLE Surgery CASCADE CONSTRAINTS;
DROP TABLE Medicine CASCADE CONSTRAINTS;

-- Confirm Changes
COMMIT;